[build-system]
requires = ["setuptools>=42.0.0", "wheel>=0.37"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip = [".venv", ".git", ".cache"]
line_length = 88

[tool.black]
line-length = 88
