[database]
# One of ["postgresql", "sqlite"]
type = "sqlite"

[caching]
host = "localhost"
database = 1  # Database ndex -- Optional.
# If authentication exists
# username = "riemann"
# password = "riemann"

[database.sqlite]
database = "riemann.db"

[database.postgresql]
host = "localhost"
port = 5432
user = "riemann"
dbname = "riemann"
password = "riemann"

[logging]
# Any of ["file", "stderr", "discord"]
type = "file"

[logging.file]
path = "riemann.log"

[logging.discord]
channel-id = 12345678
